# Generated by Django 4.1.3 on 2022-12-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-id']},
        ),
    ]
