# Generated by Django 4.1.3 on 2022-12-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/upload'),
        ),
    ]
